version: '3.8'

services:
  laravel-app:
    build: .
    container_name: laravel_app
    ports:
      - "11001:8001"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
    depends_on: []
